@startuml UseCases
left to right direction
skin rose

actor Player

package CanvasEdition{

    usecase CreateGraffiti
    usecase EnterGraffitiEdition
    usecase DeleteGraffiti

    CreateGraffiti .> EnterGraffitiEdition : Performs

    package GraffitiEdition #LightGray {

        usecase DrawLine
        usecase UndoLine
        usecase ChangeWholePosition
        usecase ChangeWholeScale
    }

    usecase ChangeSprayThickness
    usecase ChangeSprayColor
}


Player ..> CreateGraffiti
Player ..> EnterGraffitiEdition
Player ..> DeleteGraffiti
Player ..> ChangeSprayThickness
Player ..> ChangeSprayColor
Player ..> DrawLine
Player ..> UndoLine
Player ..> ChangeWholePosition
Player ..> ChangeWholeScale